version: '3.7'
services:
  db:
    image: postgres
    restart: always
    platform: linux/x86_64
    networks:
      - default
    ports:
      - "5432:5432"
    container_name: postgres_store

  api:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      - db