CREATE TABLE IF NOT EXISTS file_object(
    id BIGSERIAL PRIMARY KEY,
    owner_id VARCHAR(26) NOT NULL,
    name VARCHAR(50) NOT NULL,
    type VARCHAR(10) NOT NULL,
    size BIGINT DEFAULT 0,
    deleted BOOLEAN DEFAULT FALSE,
    storage_location VARCHAR(200) NOT NULL,
    created_at TIMESTAMP(6) WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP(6) NOT NULL
);

